################################################################################
# Automatically-generated file. Do not edit!
################################################################################

O_SRCS := 
CPP_SRCS := 
LD_SRCS := 
S67_SRCS := 
CMD_SRCS := 
CXX_SRCS := 
CMD_UPPER_SRCS := 
C43_SRCS := 
S55_SRCS := 
C62_SRCS := 
S_UPPER_SRCS := 
A_SRCS := 
C55_SRCS := 
SA_SRCS := 
C_UPPER_SRCS := 
OBJ_SRCS := 
S62_SRCS := 
LIB_SRCS := 
ASM_SRCS := 
S??_SRCS := 
C++_SRCS := 
ASM_UPPER_SRCS := 
C_SRCS := 
C67_SRCS := 
S_SRCS := 
S43_SRCS := 
OPT_SRCS := 
C64_SRCS := 
C??_SRCS := 
CC_SRCS := 
S64_SRCS := 
OBJS := 
S_DEPS := 
S62_DEPS := 
S_UPPER_DEPS := 
C64_DEPS := 
ASM_DEPS := 
CC_DEPS := 
S55_DEPS := 
C67_DEPS := 
C??_DEPS := 
CPP_DEPS := 
S??_DEPS := 
C_DEPS := 
MSP430_EXECUTABLE_OUTPUTS := 
C62_DEPS := 
CXX_DEPS := 
C++_DEPS := 
ASM_UPPER_DEPS := 
C43_DEPS := 
S67_DEPS := 
SA_DEPS := 
S43_DEPS := 
OPT_DEPS := 
S64_DEPS := 
C55_DEPS := 
C_UPPER_DEPS := 
C_DEPS__QTD := 
OBJS__QTD := 
OPT_DEPS__QTD := 
SA_DEPS__QTD := 
S55_DEPS__QTD := 
C43_DEPS__QTD := 
C67_DEPS__QTD := 
CPP_DEPS__QTD := 
CC_DEPS__QTD := 
ASM_DEPS__QTD := 
C??_DEPS__QTD := 
MSP430_EXECUTABLE_OUTPUTS__QTD := 
S??_DEPS__QTD := 
S_UPPER_DEPS__QTD := 
S64_DEPS__QTD := 
ASM_UPPER_DEPS__QTD := 
C++_DEPS__QTD := 
C62_DEPS__QTD := 
C_UPPER_DEPS__QTD := 
C55_DEPS__QTD := 
S62_DEPS__QTD := 
S43_DEPS__QTD := 
S_DEPS__QTD := 
S67_DEPS__QTD := 
CXX_DEPS__QTD := 
C64_DEPS__QTD := 

# Every subdirectory with source files must be described here
SUBDIRS := \
module/C \
. \

